package com.empresa.asiscontrol.auditoria.entity;

public enum AuditAction {
    LOGIN,
    LOGOUT,
    ACCESO_DENEGADO,
    CREAR_USUARIO,
    MODIFICAR_USUARIO,
    DESACTIVAR_USUARIO,
    ASIGNAR_ROL,
    REVOCAR_ROL,
    CREAR_AREA,
    MODIFICAR_AREA,
    CREAR_CARGO,
    MODIFICAR_CARGO,
    CREAR_EMPLEADO,
    MODIFICAR_EMPLEADO,
    DESACTIVAR_EMPLEADO,
    ASIGNAR_SUPERVISOR,
    CERRAR_ASIGNACION_SUPERVISOR,
    CREAR_CUADRILLA,
    MODIFICAR_CUADRILLA,
    ASIGNAR_SUPERVISOR_CUADRILLA,
    AGREGAR_EMPLEADO_CUADRILLA,
    RETIRAR_EMPLEADO_CUADRILLA
}
