spring:
  jpa:
    show-sql: false
  session:
    jdbc:
      cleanup-cron: "0 * * * * *"

server:
  servlet:
    session:
      timeout: 2m
      cookie:
        name: asis_test_session
        secure: false

asiscontrol:
  security:
    mfa-encryption-key: AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8=
    frontend-origins: http://localhost

