spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=true&requireSSL=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}

server:
  servlet:
    session:
      cookie:
        name: __Host-asis_session
        secure: true

logging:
  level:
    root: INFO
    com.empresa.asiscontrol: INFO

